<script lang="ts">
	import { enhance } from '$app/forms';
	import { clsx } from 'clsx';
	import type { PageData, ActionData } from './$types';
	import { uiStore } from '$lib/stores/ui.store.svelte';
	import type { Product } from '$lib/types';
	import { Plus, Pencil, ToggleLeft, ToggleRight, Package, X, RefreshCw } from 'lucide-svelte';

	function generateSlug(name: string): string {
		return name
			.toLowerCase()
			.normalize('NFD')
			.replace(/[̀-ͯ]/g, '')
			.replace(/[^a-z0-9\s-]/g, '')
			.trim()
			.replace(/\s+/g, '-')
			.replace(/-+/g, '-');
	}

	let slugInput = $state('');
	let slugAutoGenerated = $state(true);

	function onNameInput(e: Event) {
		if (slugAutoGenerated) {
			slugInput = generateSlug((e.target as HTMLInputElement).value);
		}
	}

	function onSlugInput(e: Event) {
		slugInput = (e.target as HTMLInputElement).value;
		slugAutoGenerated = false;
	}

	$effect(() => {
		if (showModal) {
			slugInput = editProduct?.slug ?? '';
			slugAutoGenerated = !editProduct;
		}
	});

	interface Props {
		data: PageData;
		form: ActionData;
	}

	let { data, form }: Props = $props();

	$effect(() => {
		if ((form as { success?: boolean } | null)?.success) {
			uiStore.success('Operação realizada com sucesso!');
			showModal = false;
			editProduct = null;
		}
		if ((form as { error?: string } | null)?.error) {
			uiStore.error((form as { error: string }).error);
		}
	});

	let showModal = $state(false);
	let editProduct = $state<Product | null>(null);

	function openCreate() {
		editProduct = null;
		showModal = true;
	}

	function openEdit(product: Product) {
		editProduct = product;
		showModal = true;
	}

	function formatPrice(v: number) {
		return v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
	}

	const statusLabel: Record<string, string> = {
		approved: 'Aprovado',
		pending_payment: 'Aguardando',
		paid: 'Pago',
		processing: 'Processando',
		shipped: 'Enviado',
		delivered: 'Entregue',
		cancelled: 'Cancelado'
	};
</script>

<svelte:head>
	<title>Produtos — Admin</title>
</svelte:head>

<!-- Modal -->
{#if showModal}
	<div
		class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
		role="dialog"
		aria-modal="true"
	>
		<div class="w-full max-w-lg rounded-2xl bg-white shadow-xl overflow-y-auto max-h-[90vh]">
			<div class="flex items-center justify-between border-b border-gray-100 px-6 py-4">
				<h2 class="font-semibold text-gray-900">
					{editProduct ? 'Editar produto' : 'Novo produto'}
				</h2>
				<button
					onclick={() => (showModal = false)}
					class="rounded-lg p-1.5 text-gray-400 hover:bg-gray-100"
				>
					<X class="h-5 w-5" />
				</button>
			</div>

			<form
				method="POST"
				action={editProduct ? '?/update' : '?/create'}
				use:enhance={() => {
					return async ({ update }) => {
						await update({ reset: !editProduct });
					};
				}}
				class="p-6 space-y-4"
			>
				{#if editProduct}
					<input type="hidden" name="id" value={editProduct.id} />
				{/if}

				<div class="grid grid-cols-2 gap-4">
					<div class="col-span-2">
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-name">
							Nome *
						</label>
						<input
							id="prod-name"
							name="name"
							type="text"
							required
							value={editProduct?.name ?? ''}
							oninput={onNameInput}
							class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100"
						/>
					</div>

					<div class="col-span-2">
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-slug">
							Slug (URL) *
						</label>
						<div class="flex gap-2">
							<input
								id="prod-slug"
								name="slug"
								type="text"
								required
								bind:value={slugInput}
								oninput={onSlugInput}
								placeholder="ex: racao-premium-adulto"
								class="flex-1 rounded-xl border border-gray-200 px-3 py-2.5 font-mono text-sm outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100"
							/>
							<button
								type="button"
								title="Regenerar a partir do nome"
								onclick={() => {
									const nameEl = document.getElementById('prod-name') as HTMLInputElement | null;
									if (nameEl) { slugInput = generateSlug(nameEl.value); slugAutoGenerated = true; }
								}}
								class="flex items-center gap-1 rounded-xl border border-gray-200 px-3 py-2 text-xs font-medium text-gray-500 hover:bg-gray-50 transition-colors"
							>
								<RefreshCw class="h-3.5 w-3.5" />
								Auto
							</button>
						</div>
						<p class="mt-1 text-xs text-gray-400">
							URL: /store/produto/<span class="font-mono text-gray-600">{slugInput || '...'}</span>
						</p>
					</div>

					<div>
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-brand">
							Marca *
						</label>
						<input
							id="prod-brand"
							name="brand"
							type="text"
							required
							value={editProduct?.brand ?? ''}
							class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100"
						/>
					</div>

					<div>
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-category">
							Categoria
						</label>
						<select
							id="prod-category"
							name="category_id"
							class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-400"
						>
							<option value="">Sem categoria</option>
							{#each data.categories as cat}
								<option value={cat.id} selected={editProduct?.category_id === cat.id}>
									{cat.name}
								</option>
							{/each}
						</select>
					</div>

					<div>
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-price">
							Preço (R$) *
						</label>
						<input
							id="prod-price"
							name="price"
							type="number"
							step="0.01"
							min="0"
							required
							value={editProduct?.price ?? ''}
							class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100"
						/>
					</div>

					<div>
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-orig-price">
							Preço original (R$)
						</label>
						<input
							id="prod-orig-price"
							name="original_price"
							type="number"
							step="0.01"
							min="0"
							value={editProduct?.original_price ?? ''}
							class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100"
						/>
					</div>

					<div>
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-stock">
							Estoque
						</label>
						<input
							id="prod-stock"
							name="stock_quantity"
							type="number"
							min="0"
							value={editProduct?.stock_quantity ?? 0}
							class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100"
						/>
					</div>

					<div>
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-tag">
							Tag (ex: Oferta, Novo)
						</label>
						<input
							id="prod-tag"
							name="tag"
							type="text"
							value={editProduct?.tag ?? ''}
							class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100"
						/>
					</div>

					<div class="col-span-2">
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-desc">
							Descrição *
						</label>
						<textarea
							id="prod-desc"
							name="description"
							rows={3}
							required
							class="w-full resize-none rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100"
						>{editProduct?.description ?? ''}</textarea>
					</div>

					<div class="col-span-2">
						<label class="mb-1 block text-xs font-medium text-gray-600" for="prod-image">
							URL da imagem
						</label>
						<input
							id="prod-image"
							name="image_url"
							type="url"
							value={editProduct?.image_url ?? ''}
							class="w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100"
						/>
					</div>

					<div class="col-span-2 flex items-center gap-3">
						<input
							id="prod-active"
							name="is_active"
							type="checkbox"
							value="true"
							checked={editProduct ? editProduct.is_active : true}
							class="h-4 w-4 rounded border-gray-300 text-primary-600"
						/>
						<label for="prod-active" class="text-sm font-medium text-gray-700">
							Produto ativo (visível na loja)
						</label>
					</div>
				</div>

				<div class="flex justify-end gap-3 pt-2">
					<button
						type="button"
						onclick={() => (showModal = false)}
						class="rounded-xl border border-gray-200 px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-50"
					>
						Cancelar
					</button>
					<button
						type="submit"
						class="rounded-xl bg-primary-500 px-4 py-2 text-sm font-semibold text-white hover:bg-primary-600"
					>
						{editProduct ? 'Salvar alterações' : 'Criar produto'}
					</button>
				</div>
			</form>
		</div>
	</div>
{/if}

<!-- Page -->
<div>
	<div class="mb-6 flex items-center justify-between">
		<div>
			<h1 class="text-2xl font-bold text-gray-900">Produtos</h1>
			<p class="mt-1 text-sm text-gray-500">{data.products.length} produtos cadastrados</p>
		</div>
		<button
			onclick={openCreate}
			class="flex items-center gap-2 rounded-xl bg-primary-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-600 transition-colors"
		>
			<Plus class="h-4 w-4" />
			Novo produto
		</button>
	</div>

	{#if data.products.length === 0}
		<div class="rounded-2xl border border-dashed border-gray-200 bg-white p-12 text-center">
			<Package class="mx-auto mb-3 h-10 w-10 text-gray-300" />
			<p class="font-medium text-gray-500">Nenhum produto cadastrado</p>
			<button
				onclick={openCreate}
				class="mt-4 inline-flex items-center gap-2 rounded-xl bg-primary-500 px-4 py-2 text-sm font-semibold text-white hover:bg-primary-600"
			>
				<Plus class="h-4 w-4" />
				Criar primeiro produto
			</button>
		</div>
	{:else}
		<div class="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm">
			<table class="w-full text-sm">
				<thead class="border-b border-gray-100 bg-gray-50">
					<tr>
						<th class="px-4 py-3 text-left font-medium text-gray-500">Produto</th>
						<th class="px-4 py-3 text-left font-medium text-gray-500 hidden md:table-cell">Categoria</th>
						<th class="px-4 py-3 text-right font-medium text-gray-500">Preço</th>
						<th class="px-4 py-3 text-center font-medium text-gray-500 hidden sm:table-cell">Estoque</th>
						<th class="px-4 py-3 text-center font-medium text-gray-500">Status</th>
						<th class="px-4 py-3 text-right font-medium text-gray-500">Ações</th>
					</tr>
				</thead>
				<tbody class="divide-y divide-gray-50">
					{#each data.products as product (product.id)}
						<tr class="hover:bg-gray-50 transition-colors">
							<td class="px-4 py-3">
								<div>
									<p class="font-medium text-gray-900">{product.name}</p>
									<p class="text-xs text-gray-400">{product.brand}</p>
								</div>
							</td>
							<td class="px-4 py-3 text-gray-500 hidden md:table-cell">
								{product.category?.name ?? '—'}
							</td>
							<td class="px-4 py-3 text-right">
								<p class="font-semibold text-gray-900">{formatPrice(product.price)}</p>
								{#if product.original_price}
									<p class="text-xs text-gray-400 line-through">{formatPrice(product.original_price)}</p>
								{/if}
							</td>
							<td class="px-4 py-3 text-center hidden sm:table-cell">
								<span
									class={clsx(
										'inline-flex rounded-full px-2 py-0.5 text-xs font-medium',
										product.stock_quantity > 10
											? 'bg-green-50 text-green-700'
											: product.stock_quantity > 0
												? 'bg-amber-50 text-amber-700'
												: 'bg-red-50 text-red-600'
									)}
								>
									{product.stock_quantity} un.
								</span>
							</td>
							<td class="px-4 py-3 text-center">
								<form method="POST" action="?/toggle" use:enhance>
									<input type="hidden" name="id" value={product.id} />
									<input type="hidden" name="is_active" value={String(!product.is_active)} />
									<button
										type="submit"
										class={clsx(
											'inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium transition-colors',
											product.is_active
												? 'bg-green-50 text-green-700 hover:bg-green-100'
												: 'bg-gray-100 text-gray-500 hover:bg-gray-200'
										)}
										title={product.is_active ? 'Desativar' : 'Ativar'}
									>
										{#if product.is_active}
											<ToggleRight class="h-3.5 w-3.5" />
											Ativo
										{:else}
											<ToggleLeft class="h-3.5 w-3.5" />
											Inativo
										{/if}
									</button>
								</form>
							</td>
							<td class="px-4 py-3 text-right">
								<div class="flex items-center justify-end gap-1">
									<a
										href="/store/produto/{product.slug}"
										target="_blank"
										rel="noopener"
										class="rounded-lg p-1.5 text-gray-300 hover:bg-gray-100 hover:text-gray-600 transition-colors"
										title="Ver produto"
									>
										<svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
											<path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>
											<polyline points="15,3 21,3 21,9"/>
											<line x1="10" y1="14" x2="21" y2="3"/>
										</svg>
									</a>
									<button
										onclick={() => openEdit(product)}
										class="rounded-lg p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-600 transition-colors"
										title="Editar"
									>
										<Pencil class="h-4 w-4" />
									</button>
								</div>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{/if}
</div>
