// This file is auto-generated by: npm run db:types
// To regenerate: supabase gen types typescript --project-id <PROJECT_ID> > src/lib/types/database.types.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
	__InternalSupabase: { PostgrestVersion: '12' };
	public: {
		Tables: {
			profiles: {
				Row: {
					id: string;
					full_name: string;
					phone: string | null;
					cpf: string | null;
					avatar_url: string | null;
					address_street: string | null;
					address_city: string | null;
					address_state: string | null;
					address_zip: string | null;
					whatsapp_opt_in: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id: string;
					full_name: string;
					phone?: string | null;
					cpf?: string | null;
					avatar_url?: string | null;
					address_street?: string | null;
					address_city?: string | null;
					address_state?: string | null;
					address_zip?: string | null;
					whatsapp_opt_in?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					full_name?: string;
					phone?: string | null;
					cpf?: string | null;
					avatar_url?: string | null;
					address_street?: string | null;
					address_city?: string | null;
					address_state?: string | null;
					address_zip?: string | null;
					whatsapp_opt_in?: boolean;
					updated_at?: string;
				};
				Relationships: [];
			};
			pets: {
				Row: {
					id: string;
					owner_id: string;
					name: string;
					species: 'dog' | 'cat' | 'bird' | 'rabbit' | 'other';
					breed: string | null;
					size: 'small' | 'medium' | 'large' | 'extra_large' | null;
					birth_date: string | null;
					weight_kg: number | null;
					color: string | null;
					notes: string | null;
					avatar_url: string | null;
					is_active: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					owner_id: string;
					name: string;
					species?: 'dog' | 'cat' | 'bird' | 'rabbit' | 'other';
					breed?: string | null;
					size?: 'small' | 'medium' | 'large' | 'extra_large' | null;
					birth_date?: string | null;
					weight_kg?: number | null;
					color?: string | null;
					notes?: string | null;
					avatar_url?: string | null;
					is_active?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					name?: string;
					species?: 'dog' | 'cat' | 'bird' | 'rabbit' | 'other';
					breed?: string | null;
					size?: 'small' | 'medium' | 'large' | 'extra_large' | null;
					birth_date?: string | null;
					weight_kg?: number | null;
					color?: string | null;
					notes?: string | null;
					avatar_url?: string | null;
					is_active?: boolean;
					updated_at?: string;
				};
				Relationships: [];
			};
			services: {
				Row: {
					id: string;
					slug: string;
					name: string;
					description: string;
					short_desc: string;
					price_from: number;
					duration_min: number;
					image_url: string | null;
					is_active: boolean;
					display_order: number;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					slug: string;
					name: string;
					description: string;
					short_desc: string;
					price_from: number;
					duration_min: number;
					image_url?: string | null;
					is_active?: boolean;
					display_order?: number;
				};
				Update: {
					name?: string;
					description?: string;
					short_desc?: string;
					price_from?: number;
					duration_min?: number;
					image_url?: string | null;
					is_active?: boolean;
					display_order?: number;
				};
				Relationships: [];
			};
			appointments: {
				Row: {
					id: string;
					user_id: string;
					pet_id: string;
					service_id: string;
					status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
					scheduled_at: string;
					duration_min: number;
					price_charged: number | null;
					notes: string | null;
					internal_notes: string | null;
					cancelled_at: string | null;
					cancellation_reason: string | null;
					whatsapp_notified: boolean;
					notification_sid: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					pet_id: string;
					service_id: string;
					status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
					scheduled_at: string;
					duration_min: number;
					price_charged?: number | null;
					notes?: string | null;
					internal_notes?: string | null;
					whatsapp_notified?: boolean;
					notification_sid?: string | null;
				};
				Update: {
					status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
					scheduled_at?: string;
					price_charged?: number | null;
					notes?: string | null;
					internal_notes?: string | null;
					cancelled_at?: string | null;
					cancellation_reason?: string | null;
					whatsapp_notified?: boolean;
					notification_sid?: string | null;
					updated_at?: string;
				};
				Relationships: [];
			};
		};
		Views: {
			appointments_full: {
				Row: {
					id: string;
					status: string;
					scheduled_at: string;
					duration_min: number;
					price_charged: number | null;
					notes: string | null;
					whatsapp_notified: boolean;
					created_at: string;
					updated_at: string;
					user_id: string;
					user_name: string;
					user_phone: string | null;
					pet_id: string;
					pet_name: string;
					pet_species: string;
					pet_breed: string | null;
					service_id: string;
					service_slug: string;
					service_name: string;
					service_image_url: string | null;
				};
				Relationships: [];
			};
		};
		Enums: {
			pet_species: 'dog' | 'cat' | 'bird' | 'rabbit' | 'other';
			pet_size: 'small' | 'medium' | 'large' | 'extra_large';
			appointment_status:
				| 'pending'
				| 'confirmed'
				| 'in_progress'
				| 'completed'
				| 'cancelled'
				| 'no_show';
		};
		Functions: Record<string, never>;
	};
};
