// This file is auto-generated by: npm run db:types
// To regenerate: supabase gen types typescript --project-id <PROJECT_ID> > src/lib/types/database.types.ts
// Note: manually updated to include admin panel tables (caretakers, schedules, blocks)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
	__InternalSupabase: { PostgrestVersion: '12' };
	public: {
		Tables: {
			profiles: {
				Row: {
					id: string;
					full_name: string;
					phone: string | null;
					cpf: string | null;
					avatar_url: string | null;
					address_street: string | null;
					address_city: string | null;
					address_state: string | null;
					address_zip: string | null;
					whatsapp_opt_in: boolean;
					role: 'customer' | 'caretaker' | 'admin' | 'root_admin';
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id: string;
					full_name: string;
					phone?: string | null;
					cpf?: string | null;
					avatar_url?: string | null;
					address_street?: string | null;
					address_city?: string | null;
					address_state?: string | null;
					address_zip?: string | null;
					whatsapp_opt_in?: boolean;
					role?: 'customer' | 'caretaker' | 'admin' | 'root_admin';
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					full_name?: string;
					phone?: string | null;
					cpf?: string | null;
					avatar_url?: string | null;
					address_street?: string | null;
					address_city?: string | null;
					address_state?: string | null;
					address_zip?: string | null;
					whatsapp_opt_in?: boolean;
					role?: 'customer' | 'caretaker' | 'admin' | 'root_admin';
					updated_at?: string;
				};
				Relationships: [];
			};
			pets: {
				Row: {
					id: string;
					owner_id: string;
					name: string;
					species: 'dog' | 'cat' | 'bird' | 'rabbit' | 'other';
					breed: string | null;
					size: 'small' | 'medium' | 'large' | 'extra_large' | null;
					birth_date: string | null;
					weight_kg: number | null;
					color: string | null;
					notes: string | null;
					avatar_url: string | null;
					is_active: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					owner_id: string;
					name: string;
					species?: 'dog' | 'cat' | 'bird' | 'rabbit' | 'other';
					breed?: string | null;
					size?: 'small' | 'medium' | 'large' | 'extra_large' | null;
					birth_date?: string | null;
					weight_kg?: number | null;
					color?: string | null;
					notes?: string | null;
					avatar_url?: string | null;
					is_active?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					name?: string;
					species?: 'dog' | 'cat' | 'bird' | 'rabbit' | 'other';
					breed?: string | null;
					size?: 'small' | 'medium' | 'large' | 'extra_large' | null;
					birth_date?: string | null;
					weight_kg?: number | null;
					color?: string | null;
					notes?: string | null;
					avatar_url?: string | null;
					is_active?: boolean;
					updated_at?: string;
				};
				Relationships: [];
			};
			services: {
				Row: {
					id: string;
					slug: string;
					name: string;
					description: string;
					short_desc: string;
					price_from: number;
					duration_min: number;
					image_url: string | null;
					is_active: boolean;
					display_order: number;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					slug: string;
					name: string;
					description: string;
					short_desc: string;
					price_from: number;
					duration_min: number;
					image_url?: string | null;
					is_active?: boolean;
					display_order?: number;
				};
				Update: {
					name?: string;
					description?: string;
					short_desc?: string;
					price_from?: number;
					duration_min?: number;
					image_url?: string | null;
					is_active?: boolean;
					display_order?: number;
				};
				Relationships: [];
			};
			appointments: {
				Row: {
					id: string;
					user_id: string;
					pet_id: string;
					service_id: string;
					caretaker_id: string | null;
					status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
					scheduled_at: string;
					duration_min: number;
					price_charged: number | null;
					notes: string | null;
					internal_notes: string | null;
					cancelled_at: string | null;
					cancellation_reason: string | null;
					whatsapp_notified: boolean;
					notification_sid: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					pet_id: string;
					service_id: string;
					caretaker_id?: string | null;
					status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
					scheduled_at: string;
					duration_min: number;
					price_charged?: number | null;
					notes?: string | null;
					internal_notes?: string | null;
					whatsapp_notified?: boolean;
					notification_sid?: string | null;
				};
				Update: {
					caretaker_id?: string | null;
					status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
					scheduled_at?: string;
					price_charged?: number | null;
					notes?: string | null;
					internal_notes?: string | null;
					cancelled_at?: string | null;
					cancellation_reason?: string | null;
					whatsapp_notified?: boolean;
					notification_sid?: string | null;
					updated_at?: string;
				};
				Relationships: [];
			};
			caretakers: {
				Row: {
					id: string;
					user_id: string | null;
					name: string;
					bio: string | null;
					specialties: string[];
					is_active: boolean;
					avatar_url: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id?: string | null;
					name: string;
					bio?: string | null;
					specialties?: string[];
					is_active?: boolean;
					avatar_url?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					user_id?: string | null;
					name?: string;
					bio?: string | null;
					specialties?: string[];
					is_active?: boolean;
					avatar_url?: string | null;
					updated_at?: string;
				};
				Relationships: [];
			};
			caretaker_schedules: {
				Row: {
					id: string;
					caretaker_id: string;
					day_of_week: number;
					start_time: string;
					end_time: string;
					is_active: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					caretaker_id: string;
					day_of_week: number;
					start_time: string;
					end_time: string;
					is_active?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					day_of_week?: number;
					start_time?: string;
					end_time?: string;
					is_active?: boolean;
					updated_at?: string;
				};
				Relationships: [];
			};
			caretaker_blocked_slots: {
				Row: {
					id: string;
					caretaker_id: string;
					blocked_date: string;
					start_time: string | null;
					end_time: string | null;
					reason: string | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					caretaker_id: string;
					blocked_date: string;
					start_time?: string | null;
					end_time?: string | null;
					reason?: string | null;
					created_at?: string;
				};
				Update: {
					blocked_date?: string;
					start_time?: string | null;
					end_time?: string | null;
					reason?: string | null;
				};
				Relationships: [];
			};
			permissions: {
				Row: {
					id: string;
					name: string;
					description: string | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					name: string;
					description?: string | null;
					created_at?: string;
				};
				Update: {
					id?: string;
					name?: string;
					description?: string | null;
				};
				Relationships: [];
			};
			roles: {
				Row: {
					id: string;
					name: string;
					description: string | null;
					is_system: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					name: string;
					description?: string | null;
					is_system?: boolean;
					created_at?: string;
				};
				Update: {
					id?: string;
					name?: string;
					description?: string | null;
					is_system?: boolean;
				};
				Relationships: [];
			};
			role_permissions: {
				Row: { role_id: string; permission_id: string };
				Insert: { role_id: string; permission_id: string };
				Update: { role_id?: string; permission_id?: string };
				Relationships: [];
			};
			user_roles: {
				Row: {
					user_id: string;
					role_id: string;
					assigned_at: string;
					assigned_by: string | null;
				};
				Insert: {
					user_id: string;
					role_id: string;
					assigned_at?: string;
					assigned_by?: string | null;
				};
				Update: {
					user_id?: string;
					role_id?: string;
					assigned_at?: string;
					assigned_by?: string | null;
				};
				Relationships: [];
			};
			product_categories: {
				Row: {
					id: string;
					slug: string;
					name: string;
					description: string | null;
					display_order: number;
					is_active: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					slug: string;
					name: string;
					description?: string | null;
					display_order?: number;
					is_active?: boolean;
					created_at?: string;
				};
				Update: {
					slug?: string;
					name?: string;
					description?: string | null;
					display_order?: number;
					is_active?: boolean;
				};
				Relationships: [];
			};
			products: {
				Row: {
					id: string;
					category_id: string | null;
					slug: string;
					sku: string | null;
					name: string;
					brand: string;
					description: string;
					short_description: string | null;
					price: number;
					original_price: number | null;
					stock_quantity: number;
					image_url: string | null;
					images: string[];
					tag: string | null;
					is_active: boolean;
					display_order: number;
					rating: number;
					review_count: number;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					category_id?: string | null;
					slug: string;
					sku?: string | null;
					name: string;
					brand: string;
					description: string;
					short_description?: string | null;
					price: number;
					original_price?: number | null;
					stock_quantity?: number;
					image_url?: string | null;
					images?: string[];
					tag?: string | null;
					is_active?: boolean;
					display_order?: number;
					rating?: number;
					review_count?: number;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					category_id?: string | null;
					slug?: string;
					sku?: string | null;
					name?: string;
					brand?: string;
					description?: string;
					short_description?: string | null;
					price?: number;
					original_price?: number | null;
					stock_quantity?: number;
					image_url?: string | null;
					images?: string[];
					tag?: string | null;
					is_active?: boolean;
					display_order?: number;
					rating?: number;
					review_count?: number;
					updated_at?: string;
				};
				Relationships: [];
			};
			orders: {
				Row: {
					id: string;
					user_id: string;
					status: 'pending_payment' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
					subtotal: number;
					shipping: number;
					total: number;
					shipping_name: string | null;
					shipping_address: string | null;
					shipping_city: string | null;
					shipping_state: string | null;
					shipping_zip: string | null;
					mp_payment_id: string | null;
					mp_status: string | null;
					notes: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					status?: 'pending_payment' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
					subtotal: number;
					shipping?: number;
					total: number;
					shipping_name?: string | null;
					shipping_address?: string | null;
					shipping_city?: string | null;
					shipping_state?: string | null;
					shipping_zip?: string | null;
					mp_payment_id?: string | null;
					mp_status?: string | null;
					notes?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					status?: 'pending_payment' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
					mp_payment_id?: string | null;
					mp_status?: string | null;
					notes?: string | null;
					updated_at?: string;
				};
				Relationships: [];
			};
			order_items: {
				Row: {
					id: string;
					order_id: string;
					product_id: string | null;
					product_name: string;
					product_brand: string;
					unit_price: number;
					quantity: number;
					subtotal: number;
					created_at: string;
				};
				Insert: {
					id?: string;
					order_id: string;
					product_id?: string | null;
					product_name: string;
					product_brand: string;
					unit_price: number;
					quantity: number;
					subtotal: number;
					created_at?: string;
				};
				Update: {
					quantity?: number;
					subtotal?: number;
				};
				Relationships: [];
			};
			payments: {
				Row: {
					id: string;
					order_id: string;
					mp_payment_id: string;
					mp_status: string;
					mp_status_detail: string | null;
					mp_payment_method: string | null;
					mp_payment_type: string | null;
					pix_qr_code: string | null;
					pix_qr_code_base64: string | null;
					pix_expiration_date: string | null;
					boleto_url: string | null;
					boleto_barcode: string | null;
					raw_response: Record<string, unknown> | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					order_id: string;
					mp_payment_id: string;
					mp_status: string;
					mp_status_detail?: string | null;
					mp_payment_method?: string | null;
					mp_payment_type?: string | null;
					pix_qr_code?: string | null;
					pix_qr_code_base64?: string | null;
					pix_expiration_date?: string | null;
					boleto_url?: string | null;
					boleto_barcode?: string | null;
					raw_response?: Record<string, unknown> | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					mp_status?: string;
					mp_status_detail?: string | null;
					pix_qr_code?: string | null;
					pix_qr_code_base64?: string | null;
					boleto_url?: string | null;
					boleto_barcode?: string | null;
					updated_at?: string;
				};
				Relationships: [];
			};
		};
		Views: {
			appointments_full: {
				Row: {
					id: string;
					status: string;
					scheduled_at: string;
					duration_min: number;
					price_charged: number | null;
					notes: string | null;
					internal_notes: string | null;
					whatsapp_notified: boolean;
					cancelled_at: string | null;
					cancellation_reason: string | null;
					caretaker_id: string | null;
					caretaker_name: string | null;
					created_at: string;
					updated_at: string;
					user_id: string;
					user_name: string;
					user_phone: string | null;
					pet_id: string;
					pet_name: string;
					pet_species: string;
					pet_breed: string | null;
					service_id: string;
					service_slug: string;
					service_name: string;
					service_image_url: string | null;
				};
				Relationships: [];
			};
		};
		Enums: {
			pet_species: 'dog' | 'cat' | 'bird' | 'rabbit' | 'other';
			pet_size: 'small' | 'medium' | 'large' | 'extra_large';
			appointment_status:
				| 'pending'
				| 'confirmed'
				| 'in_progress'
				| 'completed'
				| 'cancelled'
				| 'no_show';
			user_role: 'customer' | 'caretaker' | 'admin' | 'root_admin';
		};
		Functions: {
			get_user_permissions: {
				Args: { p_user_id: string };
				Returns: { name: string }[];
			};
			user_has_permission: {
				Args: { p_user_id: string; p_permission: string };
				Returns: boolean;
			};
			is_admin: {
				Args: Record<string, never>;
				Returns: boolean;
			};
			is_root_admin: {
				Args: Record<string, never>;
				Returns: boolean;
			};
		};
	};
};
